/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "../desktop/src/**/*.js",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#f47a5a",
        "on-error": "#490013",
        "secondary-fixed-dim": "#ffa8e4",
        "surface-container-highest": "#242434",
        "error-container": "#a70138",
        "surface-container": "#181826",
        "on-primary-fixed-variant": "#680070",
        "surface-container-low": "#12121e",
        "on-tertiary-fixed": "#350700",
        "on-primary-fixed": "#310035",
        "primary-dim": "#eb75ee",
        "primary-container": "#e872eb",
        "tertiary-fixed": "#ff9477",
        "outline-variant": "#474754",
        "inverse-on-surface": "#555461",
        "on-surface": "#e9e6f7",
        "on-secondary-container": "#ffbce8",
        "secondary-fixed": "#ffbee9",
        "inverse-surface": "#fcf8ff",
        "surface-dim": "#0d0d18",
        "primary-fixed-dim": "#eb75ee",
        "primary-fixed": "#fb82fd",
        "secondary": "#fd92df",
        "on-secondary": "#630955",
        "primary": "#fb82fd",
        "on-tertiary-container": "#480c00",
        "surface-bright": "#2b2a3c",
        "on-background": "#e9e6f7",
        "on-secondary-fixed": "#630854",
        "secondary-dim": "#ed85d1",
        "secondary-container": "#7a2268",
        "surface-container-lowest": "#000000",
        "surface": "#0d0d18",
        "background": "#0d0d18",
        "on-primary-container": "#430048",
        "tertiary-container": "#f87d5c",
        "tertiary": "#ff8f72",
        "error": "#ff6e84",
        "outline": "#757482",
        "on-error-container": "#ffb2b9",
        "on-surface-variant": "#aba9b9",
        "on-tertiary": "#5d1200",
        "error-dim": "#d73357",
        "on-tertiary-fixed-variant": "#701902",
        "inverse-primary": "#9c2ba3",
        "on-secondary-fixed-variant": "#862c73",
        "tertiary-fixed-dim": "#fb805f",
        "surface-variant": "#242434",
        "surface-tint": "#fb82fd",
        "surface-container-high": "#1e1e2d",
        "on-primary": "#5a0061",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
