services:
  - type: web
    name: diabetic-retinopathy-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 300 --worker-tmp-dir /dev/shm --forwarded-allow-ips='*' app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
